project:
  type: website

website:
  title: "Ramblings in Chaos"
  page-footer: "Made with Quarto"
  navbar:
    left:
      - text: Home 
        href: index.qmd
        icon: house
      - text: Data Visualization
        href: data_visualisation/index.qmd
        icon: bar-chart-line
      - text: Data Wrangling
        href: data_wrangling/index.qmd
        icon: database-check
      - text: Playground
        href: playground/index.qmd
        icon: backpack2
    right:
      - icon: github
        href: "https://github.com/JoaoGarcezAurelio"
      - icon: mastodon
        href: https://mastodon.social/@JGA
      - icon: linkedin
        href: https://www.linkedin.com/in/jo%C3%A3o-santos-a4a77514/
      - icon: fingerprint
        href: https://research.manchester.ac.uk/en/persons/joao.santos
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/jgas.bsky.social
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    mainfont: Atkinson Hyperlegible
editor: visual
execute:
  freeze: auto

